XLPagerTabStrip/XL/Controllers/XLPagerTabStripViewController.m

The reason of this PR is to correct the intended behavior of ChildViewControllers of a custom container. According to Apple's document [Creating Custom Container View Controllers] (https://developer.apple.com/library/ios/featuredarticles/ViewControllerPGforiPhoneOS/CreatingCustomContainerViewControllers/CreatingCustomContainerViewControllers.html) 
`To actually inform the child view controller that an appearance transition is occurring, you call the child’s beginAppearanceTransition:animated: and endAppearanceTransition methods.`
The reason was that `viewWillAppear:` wasn't being called for the first child, so
`beginAppearanceTransition: animated:`  to tell the child that its views are about to appear or disappear. And `endAppearanceTransition` to tell the child that the view transition …

Add Appearance Behavior to PagerChildControllers

---

XLPagerTabStrip/XL/Controllers/XLPagerTabStripViewController.m

When `[self scrollDirection] == XLPagerTabStripDirectionLeft` or `[self scrollDirection] == XLPagerTabStripDirectionNone`, the delegate method `pagerTabStripViewController:updateIndicatorFromIndex:toIndex:withProgressPercentage:` never sent back a progressPercentage of 1.0 because the `fmodf` calculation would return inaccurate results. I added a check to explicitly return 1.0 when `self.containerView.contentOffset.x` is an exact multiple of `[self pageWidth]`

Fixed issue where scrollPercentage would never be equal to 1.0 

---

XLPagerTabStrip/XL/Controllers/XLPagerTabStripViewController.m

Animated flag is not respected.
if (self.skipIntermediateViewControllers && ABS(self.currentIndex - index) > 1)) should only be executed when animated is enabled.

Bug Fix - PagerTabStrip VC's moveToViewControllerAtIndex:animated:

---

XLPagerTabStrip/XL/Controllers/XLButtonBarPagerTabStripViewController.m

When you select button for current page, selected bar does not update when you scroll container scroll view. The reason is that 'shouldUpdateButtonBarView' varaible does not reset back to true, because [UIScrollViewDelegate scrollViewDidEndScrollingAnimation] is never called when you select button for current page.
I resolved this issue by avoiding current page selection by comparing NSIndexPath.item with self.currentIndex.

Bug Fix - Button Bar Selection on Current Page Issues

---

XLPagerTabStrip/XL/Controllers/XLPagerTabStripViewController.m

beginAppearanceTransition:animated: are called before addChildViewController:.
This cause a crash when a childViewController refers the parentViewController's objects such as navigationController in viewWillAppear:.
So, beginAppearanceTransition:animated: should be called after addChildViewController:.

Bug Fix - PagerTabStrip VC's updateContent

---

XLPagerTabStrip/XL/Controllers/XLTwitterPagerTabStripViewController.m

Fixed the following issue #86 https://github.com/xmartlabs/XLPagerTabStrip/issues/86 
There is a issue caused by the fact that we remove an observer before registering it.
Error : 
*** Terminating app due to uncaught exception 'NSRangeException', reason: 'Cannot remove an observer for the key path "frame" from because it is not registered as an observer.'
Added a try catch for the remove observer call in XLTwitterPagerTabStripViewController

Fixed KVC remove observer crash for XLTwitterPagerTabStripViewController

---

XLPagerTabStrip/XL/Controllers/XLButtonBarPagerTabStripViewController.m
XLPagerTabStrip/XL/Views/XLButtonBarViewCell.m

At present the demo app uses a storyboard so all the views and sub-views are initialised and sized automatically.  
Its perfectly reasonable for consumers to want to use XLPagerTabStrip components programically without either a storyboard or even a XIB, however if this approach is attempted at present...
a) A crash is experienced because the cell reuse identifier hasn't been registered
b) None of the views get a sensible frame so don't appear where you'd expect
This PR address both these issues.

Bug fix for using XLButtonBarPagerTabStripViewController without a storyboard or XIB

---

README.md
XLPagerTabStrip/XL/Controllers/XLButtonBarPagerTabStripViewController.m
XLPagerTabStrip/XL/Views/XLButtonBarView.h
XLPagerTabStrip/XL/Views/XLButtonBarView.m

... so that developers can choose how the selectedBar gets aligns as the user scrolls through view controllers.
Additionally consolidated some duplicated code into a new method contentOffsetForCellWithFrame:index: so there is a single place where the contentOffset (i.e. the selectedBar alignment) is calculated (regardless of whether the user tapped a tab/cell or scrolled the UIPageViewController).

Added (XLSelectedBarAlignment) selectedBarAlignment property to XLButtonBarView

---

Sources/ButtonBarPagerTabStripViewController.swift

This helps to subclass ButtonBarPagerTabStripViewController. In my case I wasn't able to use default initializer without parameters because `init(nibName: String?, bundle: String?)` is internal.

Made ButtonBarPagerTabStripViewController initializer public

---

Sources/TwitterPagerTabStripViewController.swift

Remove a wrong observer in TwitterPagerTabStripViewController.swift.
How to reproduce in Example project:
1. Select **PageTabController Types**
2. Select the **Twitter** tab
3. Select the **Bar** tab
4. Select **Close** to dismiss the view controller.
Then the app will crash with error **An instance of class … is being deallocated while key value observing are still registered with it**

Remove wrong observer when deinit

---

Sources/BaseButtonBarPagerTabStripViewController.swift
Sources/ButtonBarPagerTabStripViewController.swift

Addresses issue [#130](https://github.com/xmartlabs/XLPagerTabStrip/issues/130).
On BaseButtonBarPagerTabStripViewController and ButtonBarPagerTabStripViewController, the container view's height and y position is calculated using self.settings.style.buttonBarHeight, if set.

fix container view placement on custom bar height.

---

Sources/PagerTabStripViewController.swift

This PR fixes https://github.com/xmartlabs/XLPagerTabStrip/issues/242.
When `moveToViewController(at: Int, animated: Bool)` or `moveTo(viewController: UIViewController, animated: Bool)` was called, user interaction was disabled to prevent the user from interacting with the UI in the middle of a transition. Then, in `scrollViewDidEndScrollingAnimation(_:UIScrollView)`, user interaction would be enabled again. However, when passing `false` for the`animated` parameter, this method does not get called and user interaction won't be enabled again.
The fix is simple. We don't need to disable user interaction when the transition is not animated since the `contentOffset` of the scroll view gets set immediately. I tested it and can I can confirm that it works now.
In the [corresponding …

Only disable user interaction when animating (fixes Issue #242)

---

Sources/ButtonBarPagerTabStripViewController.swift

Fixes issues #343, #338 
The issue was that the collection view doesn't return the cells that are not visible, in such cases the cells weren't neither updated nor reloaded. So, what this changes do is, if a cell is not currently visible and its child controller was moved, then reload it.
* How to reproduce the issue:
* The issue is solved:

Reload not visible cells when changing current child controller

---

Sources/BaseButtonBarPagerTabStripViewController.swift
Sources/ButtonBarPagerTabStripViewController.swift

`buttonBarMinimumInteritemSpacing` was missing and misconfigured with `buttonBarMinimumLineSpacing`

Adding `buttonBarMinimumInteritemSpacing`

---

Sources/PagerTabStripViewController.swift

When using ButtonBarPagerTabStripViewController, even if I click button, since lastContentOffset was not updated, I will fix it

fix to always update lastContentOffset when scrolling

---

Sources/ButtonBarPagerTabStripViewController.swift
Sources/PagerTabStripViewController.swift

When the `moveToViewController(..)` function was called but the view wasn't visible, the index of the target viewcontroller got "saved" to the `currentIndex` property for further use. When the view indeed became visible this wasn't checked and the change to `currentIndex` was vain, issue #357.
This PR adds the `preCurrentIndex` with the sole purpose of handling this case, the currentIndex gets changed when the view isn't visible.
The index of the target viewcontroller gets "saved" to this property and then in the `viewDidAppear` function it gets checked against `currentIndex` to determine if the current child vc needs to be updated.
The downside of this approach is that the child gets updated **after** the view appears.

Fixes #357

---

Sources/ButtonBarView.swift

Fixes #322, the `contentOffset` of the `ButtonBarView` was being set animated when the swipe velocity was _high_, this caused `UIKit` to set the `contentOffset` with a constant velocity and resulted in the actual scroll to be delayed.

Fixes #322

---

Sources/BaseButtonBarPagerTabStripViewController.swift
Sources/ButtonBarPagerTabStripViewController.swift
Sources/ButtonBarViewCell.swift
Sources/IndicatorInfo.swift

There are two open pull requests that never made it into master:
- https://github.com/xmartlabs/XLPagerTabStrip/pull/323
- https://github.com/xmartlabs/XLPagerTabStrip/pull/410
I improved on the work that has been done there by making the accessibility traits work for all components/configurations included in the framework. Additionally I added the label as a property to IndicatorInfo, so that users can set accessibility labels when they are using only icons. If they are not specifying a an accessibility label, it will default to the title.

Accessibility traits + labels

---

XLPagerTabStrip.podspec

With current podspec, one .xib file is getting picked up as a source, and is getting into Xcode Compile Sources build step in CocoaPods generated project. 
New build system is more strict than the old one, and prohibits this by saying:
```
error: unexpected duplicate task: CompileXIB /Path-To-Project/Pods/XLPagerTabStrip/Sources/ButtonCell.xib (in target 'XLPagerTabStrip')
```
This behavior is described in [this CocoaPods issue](https://github.com/CocoaPods/CocoaPods/issues/7079).
This PR changes source_files search path from being * to more specific code-related one *.{h,m,swift}, thus picking only sources into sources.
This fix can be verified by installing XLPagerTabStrip, trying to build with new Build System - it will fail. Then you can remove ButtonCell.xib file from Pods -> …

Fix compilation of the project when using Xcode 9 new build system and CocoaPods

---

Example/Example/Base.lproj/Storyboard.storyboard
Example/Example/Helpers/PostCell.xib

We need to place subviews onto UITableViewCell's contentView (to use `UITableViewCell.insetsContentViewsToSafeArea`: https://developer.apple.com/documentation/uikit/uitableview/2921665-insetscontentviewstosafearea).
Fixes https://github.com/xmartlabs/XLPagerTabStrip/issues/498 (https://github.com/xmartlabs/XLPagerTabStrip/issues/498#issuecomment-418579377).
Before:
After:

[Example] Update PostCell to use contentView
